# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import my_code as module_0


def test_case_0():
    int_0 = 60
    var_0 = module_0.is_prime(int_0)
    assert var_0 is False
    var_1 = module_0.is_palindrome(var_0)
    assert var_1 is False
    module_0.is_prime(var_0)


def test_case_1():
    bool_0 = False
    module_0.is_prime(bool_0)
    float_0 = -1328.835
    with pytest.raises(ValueError):
        module_0.factorial(float_0)


def test_case_2():
    int_0 = 60
    var_0 = module_0.is_prime(int_0)
    assert var_0 is False
    var_1 = module_0.factorial(int_0)
    assert (
        var_1
        == 8320987112741390144276341183223364380754172606361245952449277696409600000000000000
    )


def test_case_3():
    int_0 = 85
    var_0 = module_0.is_prime(int_0)
    assert var_0 is False
    str_0 = "RaI}L2Qm$$l"
    var_1 = module_0.is_palindrome(str_0)
    assert var_1 is False
    var_2 = module_0.is_palindrome(var_0)
    assert var_2 is False
    var_3 = module_0.fibonacci(int_0)
    assert var_3 == 259695496911122585
    var_4 = module_0.factorial(var_2)
    assert var_4 == 1


def test_case_4():
    int_0 = 60
    var_0 = module_0.is_prime(int_0)
    assert var_0 is False
    var_1 = module_0.is_palindrome(var_0)
    assert var_1 is False


def test_case_5():
    bool_0 = True
    var_0 = module_0.fibonacci(bool_0)
    assert var_0 == 1
    float_0 = -1328.835
    object_0 = module_0.is_prime(float_0)
    assert object_0 is False
    module_0.fibonacci(float_0)


def test_case_6():
    int_0 = 60
    var_0 = module_0.is_prime(int_0)
    assert var_0 is False


def test_case_7():
    int_0 = 85
    var_0 = module_0.is_prime(int_0)
    assert var_0 is False
    var_1 = module_0.is_palindrome(var_0)
    assert var_1 is False
    var_2 = module_0.factorial(var_1)
    assert var_2 == 1


def test_case_8():
    int_0 = 69
    var_0 = module_0.is_palindrome(int_0)
    assert var_0 is False
    var_1 = module_0.is_prime(int_0)
    assert var_1 is False
    var_2 = module_0.fibonacci(var_1)
    assert var_2 == 0


def test_case_9():
    int_0 = 60
    var_0 = module_0.is_prime(int_0)
    assert var_0 is False
    var_1 = module_0.is_palindrome(int_0)
    assert var_1 is False
    var_2 = module_0.factorial(var_1)
    assert var_2 == 1
    var_3 = module_0.fibonacci(int_0)
    assert var_3 == 1548008755920


def test_case_10():
    int_0 = 233
    var_0 = module_0.is_prime(int_0)
    assert var_0 is True
    var_1 = module_0.is_palindrome(var_0)
    assert var_1 is False
    var_2 = module_0.fibonacci(var_1)
    assert var_2 == 0
    var_3 = module_0.factorial(var_0)
    assert var_3 == 1


def test_case_11():
    int_0 = 233
    var_0 = module_0.is_prime(int_0)
    assert var_0 is True
    var_1 = module_0.fibonacci(var_0)
    assert var_1 == 1


def test_case_12():
    int_0 = 2
    var_0 = module_0.is_prime(int_0)
    assert var_0 is True
    var_1 = module_0.is_palindrome(var_0)
    assert var_1 is False
